name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: "gilsondejesus"
          outputs: "github-contribution-grid-snake.svg"

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualização automática da animação Snake"
          add: "github-contribution-grid-snake.svg"
