name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação Snake com fundo preto
        uses: Platane/snk@v3
        with:
          github_user_name: "gilsondejesus"
          outputs: "github-contribution-grid-snake.svg"
          palette: "github-dark" # Define o fundo preto

      - name: Commit e push da animação
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Atualização automática da animação Snake" || echo "Nenhuma alteração para commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
